### ISSUE TITLE
Slim Variants

### ISSUE THREAD

**Issue by grahamburgsma** [futurejones/swift-arm64-docker#1]
Thanks for maintaining this. 🙌 

Any chance you could also provide slim variants like the official image does?

**Comment by futurejones** [comment]
I am currently working on slim versions and should be available soon.

**Comment by futurejones** [comment]
Slim docker images for `swift-5.5.1-release` are now available at [Swift for Arm64 Docker images ](https://hub.docker.com/r/swiftarm/swift) for the following distros.
* Ubuntu 18.04, 20.04, 21.04 and 21.10
* Debian 10 and 11

**Comment by grahamburgsma** [comment]
Thank you!
